# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Google_user',
            new_name='GoogleUser',
        ),
    ]
