# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170714_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='guser',
            new_name='author',
        ),
    ]
